import { TAFFY } from "./taffy-min"


export  default TAFFY([
    {
        "uid": 1,
        "step": "C",
        "math_name": "C",
        "alter": 0,
        "index": 1,
        "fifth_value": 0,
        "is_normal": true,
        "is_black": false,
        "loc_id": 1,
        "semitone": 0,
        "art_name": "C"
    },
    {
        "uid": 2,
        "step": "D",
        "math_name": "D",
        "alter": 0,
        "index": 2,
        "fifth_value": 2,
        "is_normal": true,
        "is_black": false,
        "loc_id": 3,
        "semitone": 2,
        "art_name": "D"
    },
    {
        "uid": 3,
        "step": "E",
        "math_name": "E",
        "alter": 0,
        "index": 3,
        "fifth_value": 4,
        "is_normal": true,
        "is_black": false,
        "loc_id": 5,
        "semitone": 4,
        "art_name": "E"
    },
    {
        "uid": 4,
        "step": "F",
        "math_name": "F",
        "alter": 0,
        "index": 4,
        "fifth_value": -1,
        "is_normal": true,
        "is_black": false,
        "loc_id": 6,
        "semitone": 5,
        "art_name": "F"
    },
    {
        "uid": 5,
        "step": "G",
        "math_name": "G",
        "alter": 0,
        "index": 5,
        "fifth_value": 1,
        "is_normal": true,
        "is_black": false,
        "loc_id": 8,
        "semitone": 7,
        "art_name": "G"
    },
    {
        "uid": 6,
        "step": "A",
        "math_name": "A",
        "alter": 0,
        "index": 6,
        "fifth_value": 3,
        "is_normal": true,
        "is_black": false,
        "loc_id": 10,
        "semitone": 9,
        "art_name": "A"
    },
    {
        "uid": 7,
        "step": "B",
        "math_name": "B",
        "alter": 0,
        "index": 7,
        "fifth_value": 5,
        "is_normal": true,
        "is_black": false,
        "loc_id": 12,
        "semitone": 11,
        "art_name": "B"
    },
    {
        "uid": 8,
        "step": "C",
        "math_name": "C+1",
        "alter": 1,
        "index": 1,
        "fifth_value": 7,
        "is_normal": true,
        "is_black": true,
        "loc_id": 2,
        "semitone": 1,
        "art_name": "C♯"
    },
    {
        "uid": 9,
        "step": "C",
        "math_name": "C-1",
        "alter": -1,
        "index": 1,
        "fifth_value": -7,
        "is_normal": false,
        "is_black": false,
        "loc_id": 12,
        "semitone": -1,
        "art_name": "C♭"
    },
    {
        "uid": 10,
        "step": "D",
        "math_name": "D+1",
        "alter": 1,
        "index": 2,
        "fifth_value": 9,
        "is_normal": true,
        "is_black": true,
        "loc_id": 4,
        "semitone": 3,
        "art_name": "D♯"
    },
    {
        "uid": 11,
        "step": "D",
        "math_name": "D-1",
        "alter": -1,
        "index": 2,
        "fifth_value": -5,
        "is_normal": true,
        "is_black": true,
        "loc_id": 2,
        "semitone": 1,
        "art_name": "D♭"
    },
    {
        "uid": 12,
        "step": "E",
        "math_name": "E+1",
        "alter": 1,
        "index": 3,
        "fifth_value": 11,
        "is_normal": false,
        "is_black": false,
        "loc_id": 6,
        "semitone": 5,
        "art_name": "E♯"
    },
    {
        "uid": 13,
        "step": "E",
        "math_name": "E-1",
        "alter": -1,
        "index": 3,
        "fifth_value": -3,
        "is_normal": true,
        "is_black": true,
        "loc_id": 4,
        "semitone": 3,
        "art_name": "E♭"
    },
    {
        "uid": 14,
        "step": "F",
        "math_name": "F+1",
        "alter": 1,
        "index": 4,
        "fifth_value": 6,
        "is_normal": true,
        "is_black": true,
        "loc_id": 7,
        "semitone": 6,
        "art_name": "F♯"
    },
    {
        "uid": 15,
        "step": "F",
        "math_name": "F-1",
        "alter": -1,
        "index": 4,
        "fifth_value": -8,
        "is_normal": false,
        "is_black": false,
        "loc_id": 5,
        "semitone": 4,
        "art_name": "F♭"
    },
    {
        "uid": 16,
        "step": "G",
        "math_name": "G+1",
        "alter": 1,
        "index": 5,
        "fifth_value": 8,
        "is_normal": true,
        "is_black": true,
        "loc_id": 9,
        "semitone": 8,
        "art_name": "G♯"
    },
    {
        "uid": 17,
        "step": "G",
        "math_name": "G-1",
        "alter": -1,
        "index": 5,
        "fifth_value": -6,
        "is_normal": true,
        "is_black": true,
        "loc_id": 7,
        "semitone": 6,
        "art_name": "G♭"
    },
    {
        "uid": 18,
        "step": "A",
        "math_name": "A+1",
        "alter": 1,
        "index": 6,
        "fifth_value": 10,
        "is_normal": true,
        "is_black": true,
        "loc_id": 11,
        "semitone": 10,
        "art_name": "A♯"
    },
    {
        "uid": 19,
        "step": "A",
        "math_name": "A-1",
        "alter": -1,
        "index": 6,
        "fifth_value": -4,
        "is_normal": true,
        "is_black": true,
        "loc_id": 9,
        "semitone": 8,
        "art_name": "A♭"
    },
    {
        "uid": 20,
        "step": "B",
        "math_name": "B+1",
        "alter": 1,
        "index": 7,
        "fifth_value": 12,
        "is_normal": false,
        "is_black": false,
        "loc_id": 1,
        "semitone": 12,
        "art_name": "B♯"
    },
    {
        "uid": 21,
        "step": "B",
        "math_name": "B-1",
        "alter": -1,
        "index": 7,
        "fifth_value": -2,
        "is_normal": true,
        "is_black": true,
        "loc_id": 11,
        "semitone": 10,
        "art_name": "B♭"
    },
    {
        "uid": 22,
        "step": "C",
        "math_name": "C+2",
        "alter": 2,
        "index": 1,
        "fifth_value": 14,
        "is_normal": false,
        "is_black": false,
        "loc_id": 3,
        "semitone": 2,
        "art_name": "C♯♯"
    },
    {
        "uid": 23,
        "step": "C",
        "math_name": "C-2",
        "alter": -2,
        "index": 1,
        "fifth_value": -14,
        "is_normal": false,
        "is_black": true,
        "loc_id": 11,
        "semitone": -2,
        "art_name": "C♭♭"
    },
    {
        "uid": 24,
        "step": "D",
        "math_name": "D+2",
        "alter": 2,
        "index": 2,
        "fifth_value": 16,
        "is_normal": false,
        "is_black": false,
        "loc_id": 5,
        "semitone": 4,
        "art_name": "D♯♯"
    },
    {
        "uid": 25,
        "step": "D",
        "math_name": "D-2",
        "alter": -2,
        "index": 2,
        "fifth_value": -12,
        "is_normal": false,
        "is_black": false,
        "loc_id": 1,
        "semitone": 0,
        "art_name": "D♭♭"
    },
    {
        "uid": 26,
        "step": "E",
        "math_name": "E+2",
        "alter": 2,
        "index": 3,
        "fifth_value": 18,
        "is_normal": false,
        "is_black": true,
        "loc_id": 7,
        "semitone": 6,
        "art_name": "E♯♯"
    },
    {
        "uid": 27,
        "step": "E",
        "math_name": "E-2",
        "alter": -2,
        "index": 3,
        "fifth_value": -10,
        "is_normal": false,
        "is_black": false,
        "loc_id": 3,
        "semitone": 2,
        "art_name": "E♭♭"
    },
    {
        "uid": 28,
        "step": "F",
        "math_name": "F+2",
        "alter": 2,
        "index": 4,
        "fifth_value": 13,
        "is_normal": false,
        "is_black": false,
        "loc_id": 8,
        "semitone": 7,
        "art_name": "F♯♯"
    },
    {
        "uid": 29,
        "step": "F",
        "math_name": "F-2",
        "alter": -2,
        "index": 4,
        "fifth_value": -15,
        "is_normal": false,
        "is_black": true,
        "loc_id": 4,
        "semitone": 3,
        "art_name": "F♭♭"
    },
    {
        "uid": 30,
        "step": "G",
        "math_name": "G+2",
        "alter": 2,
        "index": 5,
        "fifth_value": 15,
        "is_normal": false,
        "is_black": false,
        "loc_id": 10,
        "semitone": 9,
        "art_name": "G♯♯"
    },
    {
        "uid": 31,
        "step": "G",
        "math_name": "G-2",
        "alter": -2,
        "index": 5,
        "fifth_value": -13,
        "is_normal": false,
        "is_black": false,
        "loc_id": 6,
        "semitone": 5,
        "art_name": "G♭♭"
    },
    {
        "uid": 32,
        "step": "A",
        "math_name": "A+2",
        "alter": 2,
        "index": 6,
        "fifth_value": 17,
        "is_normal": false,
        "is_black": false,
        "loc_id": 12,
        "semitone": 11,
        "art_name": "A♯♯"
    },
    {
        "uid": 33,
        "step": "A",
        "math_name": "A-2",
        "alter": -2,
        "index": 6,
        "fifth_value": -11,
        "is_normal": false,
        "is_black": false,
        "loc_id": 8,
        "semitone": 7,
        "art_name": "A♭♭"
    },
    {
        "uid": 34,
        "step": "B",
        "math_name": "B+2",
        "alter": 2,
        "index": 7,
        "fifth_value": 19,
        "is_normal": false,
        "is_black": true,
        "loc_id": 2,
        "semitone": 13,
        "art_name": "B♯♯"
    },
    {
        "uid": 35,
        "step": "B",
        "math_name": "B-2",
        "alter": -2,
        "index": 7,
        "fifth_value": -9,
        "is_normal": false,
        "is_black": false,
        "loc_id": 10,
        "semitone": 9,
        "art_name": "B♭♭"
    }
]
)